---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-pvc
  labels:
    app: web
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
